### ISSUE TITLE
How to handle google.protobuf.UInt32Value field 

### ISSUE THREAD

**Issue by MrRezoo** [myyang/django-pb-model#35]
hello 
i got this error during .to_pd()
**Assignment not allowed to field "minimum_choice" in protocol message object.**
in proto file, field type is google.protobuf.UInt32Value.
do you know what's  wrong ?

with regurd,

**Comment by MrRezoo** [comment]
there is wrappers.proto on google.protobuf 
that have additional type for nullable value (optional)

**Comment by myyang** [comment]
I'm not sure this issue is related to this pkg because some information needed. Like:
1. what is the django model's field type?
2. does any constraint on target field in protobuf file?

could you try in simple example for specific field between model's field between django and protobuf and share the example to me?

**Comment by rezamobaraki** [comment]
hello  wrappers.proto  already added on google.protobuf package 
but not in your package
